### ISSUE TITLE
dkms-bbswitch - build error (Bugzilla Bug 964)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/test2#964]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 964
Date: 2014-10-16 05:51:19 +0000
From: luca &lt;<agoiza@gmail.com>&gt;
To:   OpenMandriva QA &lt;<bugs@openmandriva.org>&gt;
CC:   @tpgxyz

Last updated: 2014-10-22 07:05:45 +0000

## Comment 7361
Date: 2014-10-16 05:51:19 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

# urpmi dkms-bbswitch

    $MIRRORLIST: media/main/release/dkms-bbswitch-0.4.2-7-omv2014.0.noarch.rpm
installing dkms-bbswitch-0.4.2-7-omv2014.0.noarch.rpm from /var/cache/urpmi/rpms
Preparing...                     #############################################
      1/1: dkms-bbswitch         #############################################

Creating symlink /var/lib/dkms/bbswitch/0.4.2-7/source ->
                 /usr/src/bbswitch-0.4.2-7

DKMS: add Completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=3.15.10-nrjQL-desktop-2omv KVERSION=3.15.10-nrjQL-desktop-2omv....(bad exit status: 2)

Error! Bad return status for module build on kernel: 3.15.10-nrjQL-desktop-2omv (x86_64)
Consult the make.log in the build directory
--------------------------------------------------------------------------------

# more /var/lib/dkms/bbswitch/0.4.2-7/build/make.log 
DKMS make.log for bbswitch-0.4.2-7 for kernel 3.15.10-nrjQL-desktop-2omv (x86_64
)
Thu 16 Oct 07:33:26 CEST 2014
make -C /lib/modules/3.15.10-nrjQL-desktop-2omv/build M="$(pwd)" modules
make[1]: Entering directory `/usr/src/linux-3.15.10-nrjQL-desktop-2omv'
  CC [M]  /var/lib/dkms/bbswitch/0.4.2-7/build/bbswitch.o
/var/lib/dkms/bbswitch/0.4.2-7/build/bbswitch.c: In function ‘bbswitch_init’:
/var/lib/dkms/bbswitch/0.4.2-7/build/bbswitch.c:346:9: error: implicit declarati
on of function ‘DEVICE_ACPI_HANDLE’ [-Werror=implicit-function-declaration]
         handle = DEVICE_ACPI_HANDLE(&pdev->dev);
         ^
/var/lib/dkms/bbswitch/0.4.2-7/build/bbswitch.c:346:16: warning: assignment make
s pointer from integer without a cast [enabled by default]
         handle = DEVICE_ACPI_HANDLE(&pdev->dev);
                ^
cc1: some warnings being treated as errors
make[2]: *** [/var/lib/dkms/bbswitch/0.4.2-7/build/bbswitch.o] Error 1
make[1]: *** [_module_/var/lib/dkms/bbswitch/0.4.2-7/build] Error 2
make[1]: Leaving directory `/usr/src/linux-3.15.10-nrjQL-desktop-2omv'
make: *** [default] Error 2

## Comment 7362
Date: 2014-10-16 06:22:52 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

it seems can be solved by replacing DEVICE_ACPI_HANDLE with ACPI_HANDLE

https://github.com/Bumblebee-Project/bbswitch/issues/75

## Comment 7383
Date: 2014-10-21 20:43:58 +0000
From: @tpgxyz

I've updated dkms-bbswitch to upstream pre 0.8 version. Will post links to containers so you may want to test whether this version fixes this bug.

## Comment 7385
Date: 2014-10-22 06:19:43 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

build is fixed for me.
-------------------------------------------------------------------------

installing dkms-bbswitch-0.8-1-omv2014.0.noarch.rpm
Preparing...                     #############################################
      1/1: dkms-bbswitch         #############################################

Creating symlink /var/lib/dkms/bbswitch/0.8-1/source ->
                 /usr/src/bbswitch-0.8-1

DKMS: add Completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=3.15.10-nrjQL-desktop-2omv KVERSION=3.15.10-nrjQL-desktop-2omv....
cleaning build area....

DKMS: build Completed.

## Comment 7386
Date: 2014-10-22 07:05:45 +0000
From: @tpgxyz

(In reply to comment #3)
> build is fixed for me.

Closing as fixed
