### ISSUE TITLE
vboxadditions Build failed with kernel-nrjQL-desktop-3.11.4-1omv (Bugzilla Bug 204)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/test2#204]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 204
Date: 2013-10-16 08:47:42 +0000
From: luca &lt;<agoiza@gmail.com>&gt;
To:   OpenMandriva QA &lt;<bugs@openmandriva.org>&gt;
CC:   @berolinux, @cris-b, @itchka, @rugyada, @tpgxyz

Last updated: 2013-10-18 19:22:10 +0000

## Comment 1331
Date: 2013-10-16 08:47:42 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

vboxadditions (4.2.16-2): Installing module.
...................(bad exit status: 10)
  Build failed.  Installation skipped.

## Comment 1342
Date: 2013-10-16 11:56:22 +0000
From: @tpgxyz

Please post some logs

## Comment 1349
Date: 2013-10-16 12:34:09 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

# LC_MESSAGES=C;urpmi dkms-vboxadditions virtualbox-guest-additions
To satisfy dependencies, the following packages are going to be installed:
 Package                        Version      Release       Dist  DEpoch Arch 
(medium "main")
 dkms-vboxadditions             4.2.16       2             omv   2013.0 i586 
 virtualbox-guest-additions     4.2.16       2             omv   2013.0 i586 
 x11-driver-video-vboxvideo     4.2.16       2             omv   2013.0 i586 
11MB of additional disk space will be used.
1.5MB of packages will be retrieved.
Proceed with the installation of the 3 packages? (Y/n) Y

    http://abf-downloads.rosalinux.ru/cooker/repository/i586/media/main/release/dkms-vboxadditions-4.2.16-2-omv2013.0.i586.rpm
    http://abf-downloads.rosalinux.ru/cooker/repository/i586/media/main/release/virtualbox-guest-additions-4.2.16-2-omv2013.0.i586.rpm
    http://abf-downloads.rosalinux.ru/cooker/repository/i586/media/main/release/x11-driver-video-vboxvideo-4.2.16-2-omv2013.0.i586.rpm
installing dkms-vboxadditions-4.2.16-2-omv2013.0.i586.rpm virtualbox-guest-additions-4.2.16-2-omv2013.0.i586.rpm x11-driver-video-vboxvideo-4.2.16-2-omv2013.0.i586.rpm from /var/cache/urpmi/rpms
Preparing...                     #############################################
      1/3: dkms-vboxadditions    #############################################
+ /usr/sbin/dkms --rpm_safe_upgrade add -m vboxadditions -v 4.2.16-2

Creating symlink /var/lib/dkms/vboxadditions/4.2.16-2/source ->
                 /usr/src/vboxadditions-4.2.16-2

DKMS: add Completed.
+ /usr/sbin/dkms --rpm_safe_upgrade build -m vboxadditions -v 4.2.16-2

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=3.11.4-nrjQL-desktop-1omv -C /lib/modules/3.11.4-nrjQL-desktop-1omv/build M=/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxguest && cp /var/lib/dkms/vboxadditions/4.2.16-2/build/vboxguest/Module.symvers /var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf && make -C /lib/modules/3.11.4-nrjQL-desktop-1omv/build M=/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf && cp /var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf/Module.symvers /var/lib/dkms/vboxadditions/4.2.16-2/build/vboxvideo && make -C /lib/modules/3.11.4-nrjQL-desktop-1omv/build M=/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxvideo...............(bad exit status: 2)

Error! Bad return status for module build on kernel: 3.11.4-nrjQL-desktop-1omv (i586)
Consult the make.log in the build directory
/var/lib/dkms/vboxadditions/4.2.16-2/build/ for more information.
+ :
      2/3: virtualbox-guest-additions
                                 #############################################
vboxadd-timesync.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig vboxadd-timesync on
      3/3: x11-driver-video-vboxvideo
                                 #############################################

# more /var/lib/dkms/vboxadditions/4.2.16-2/build/make.log 
DKMS make.log for vboxadditions-4.2.16-2 for kernel 3.11.4-nrjQL-desktop-1omv (i
586)
lun 14 ott 2013, 12.31.13, CEST

## Comment 1363
Date: 2013-10-17 01:00:18 +0000
From: @berolinux

dirops API change...

/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf/dirops.c:292:5: error: unknown field ‘readdir’ specified in initializer
/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf/dirops.c:292:5: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/vboxadditions/4.2.16-2/build/vboxsf/dirops.c:292:5: warning: (near initialization for ‘sf_dir_fops.flush’) [enabled by default]

## Comment 1391
Date: 2013-10-18 10:45:11 +0000
From: @itchka

VirtualBox 4.3 is available should this be updated in the repos?
Release notes should indicated 4.2 series will not work due to API change.

## Comment 1415
Date: 2013-10-18 17:23:20 +0000
From: luca &lt;<agoiza@gmail.com>&gt;

working for me with dkms-vboxadditions-4.3.0-1-omv2013.0

## Comment 1421
Date: 2013-10-18 19:22:10 +0000
From: @cris-b

4.3.0 now available.
